model_params:
  hidden_dims: [100, 100]
  latent_dim: 20
  mask_prob: 0.03
transforms:
  train:
    window:
      args:
        window_size: 100
  test:
    window:
      args:
        window_size: 100
  seq_len: 100  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 1.0e-4
detector_params:
  num_mc_samples: 2

