model_params:
  gru_hidden_dims: [60]
  latent_dim: 20
  gmm_components: 2
transforms:
  train:
    window:
      args:
        window_size: 10
  test:
    window:
      args:
        window_size: 10
  seq_len: 10  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 1.0e-4
detector_params:
  num_mc_samples: 64

