model_params:
    filters: [32, 32, 64, 64, 64]
    kernel_sizes: [5, 5, 5, 5, 5]
    dilations: [1, 2, 4, 8, 16]
    last_n_layers_to_cat: 2
transforms:
  train:
    window:
      args:
        window_size: 100
  test:
    window:
      args:
        window_size: 100
  seq_len: 100  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 1.0e-3

