model_params:
  top_k: 5
  d_model: 64
  d_ff: 64
  num_kernels: 8
  e_layers: 4
  dropout: 0.1
epochs: 10
transforms:
  train:
    window:
      args:
        window_size: 100
  test:
    window:
      args:
        window_size: 100
  seq_len: 100  # Based on the window size of the training data
