model_params:
  d_model: 128
  n_heads: 12
  e_layers: 4
  d_ff: 320
  dropout: 0.2
transforms:
  train:
    window:
      args:
        window_size: 25
  test:
    window:
      args:
        window_size: 25
  seq_len: 25  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 1.0e-4

