model_params:
  n_trees: 500
  sample_size: 384
  extension_level: -1
transforms:
  train:
    window:
      args:
        window_size: 20
        step_size: 5
  test:
    window:
      args:
        window_size: 20
        step_size: 5
  seq_len: 20  # Based on the window size of the training data

