model_params:
  dim: 128
  out_layer_hidden_dims: [64,]
  topk: 20
  dropout_prob: 0.4
transforms:
  train:
    prediction:
      args:
        window_size: 20
        prediction_horizon: 1
        replace_labels: True
  test:
    prediction:
      args:
        window_size: 20
        prediction_horizon: 1
        replace_labels: False
  seq_len: 20  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 0.007

