model_params:
  gru_hidden_dims: [32]
  latent_dim: 32
  gmm_components: 6
transforms:
  train:
    window:
      args:
        window_size: 55
  test:
    window:
      args:
        window_size: 55
  seq_len: 55  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 1.0e-4
detector_params:
  num_mc_samples: 2

