model_params:
  n_trees: 500
  sample_size: 256
  extension_level: -1
transforms:
  train:
    window:
      args:
        window_size: 10
        step_size: 1
  test:
    window:
      args:
        window_size: 10
        step_size: 1
  seq_len: 10  # Based on the window size of the training data

