model_params:
  lstm_hidden_dims: [50, 30]
  linear_hidden_layers: [40]
  prediction_horizon: 10  # Same as set in transformation pipeline
epochs: 100
transforms:
  train:
    prediction:
      args:
        window_size: 50
        prediction_horizon: 10
        replace_labels: True
  test:
    prediction:
      args:
        window_size: 50
        prediction_horizon: 10
        replace_labels: False
  seq_len: 50  # Based on the window size of the training data
run_params:
    optimizer:
      args:
        lr: 1.0e-4

