experiment: tcn_s2s_p
model_params:
    filters: [64, 64, 64, 64, 64]
    kernel_sizes: [3, 3, 3, 3, 3]
    dilations: [1, 2, 4, 8, 16]
    last_n_layers_to_cat: 2
epochs: 100
transforms:
  train:
    prediction:
      args:
        offset: 1
        replace_labels: True
    window:
      args:
        window_size: 10
  test:
    prediction:
      args:
        offset: 1
        replace_labels: False
    window:
      args:
        window_size: 10
  seq_len: 10  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 1.0e-4
  scheduler:
    class: 'torch.optim.lr_scheduler.MultiStepLR'
    args:
      milestones: [20]
      gamma: 0.1
detector_params:
  offset: 1  # Offset same as prediction offset in pipeline
