model_params:
  dim: 96
  out_layer_hidden_dims: [96,]
  topk: 20
  dropout_prob: 0.1
transforms:
  train:
    prediction:
      args:
        window_size: 95
        prediction_horizon: 1
        replace_labels: True
  test:
    prediction:
      args:
        window_size: 95
        prediction_horizon: 1
        replace_labels: False
  seq_len: 95  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 0.002

