model_params:
  gru_hidden_dims: [224]
  latent_dim: 32
  gmm_components: 10
transforms:
  train:
    window:
      args:
        window_size: 5
  test:
    window:
      args:
        window_size: 5
  seq_len: 5  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 4.0e-5
detector_params:
  num_mc_samples: 58

