model_params:
  top_k: 6
  d_model: 64
  d_ff: 32
  num_kernels: 12
  e_layers: 4
  dropout: 0.0
transforms:
  train:
    window:
      args:
        window_size: 75
  test:
    window:
      args:
        window_size: 75
  seq_len: 75  # Based on the window size of the training data
run_params:
  optimizer:
    args:
      lr: 5.0e-05

